#!/usr/bin/env python3
import sys, poly1305, hmac
def main():
    if len(sys.argv) != 4: sys.exit(f"Usage: {sys.argv[0]} <key> <file> <tag>")
    try:
        calc = poly1305.poly1305_mac(open(sys.argv[2], 'rb').read(), bytes.fromhex(sys.argv[1]))
        print("ACCEPT" if hmac.compare_digest(calc, bytes.fromhex(sys.argv[3])) else "REJECT")
    except Exception as e: sys.exit(f"Error: {e}")
if __name__ == "__main__": main()
