#!/usr/bin/env python3
import sys, poly1305
def main():
    if len(sys.argv) != 3: sys.exit(f"Usage: {sys.argv[0]} <key> <file>")
    try:
        with open(sys.argv[2], 'rb') as f:
            print(poly1305.poly1305_mac(f.read(), bytes.fromhex(sys.argv[1])).hex())
    except Exception as e: sys.exit(f"Error: {e}")
if __name__ == "__main__": main()
